abstract class BooksStates {}
class BooksInitialState extends BooksStates{}
class GetBooksLoadingState extends BooksStates{}
class GetBooksSuccessState extends BooksStates{}
class GetBooksFailState extends BooksStates{}
class GetBooksDetailsLoadingState extends BooksStates{}
class GetBooksDetailsSuccessState extends BooksStates{}
class GetBooksDetailsFailState extends BooksStates{}
class SearchLoadingState extends BooksStates{}
class SearchSuccessState extends BooksStates{}
class SearchFailState extends BooksStates{}